name: Copy prod (secnum) DB to nightly (secnum-nightly) DB

on:
  workflow_dispatch:
  schedule:
    - cron: "03 23 * * *"

jobs:
  duplicate-prod-db-to-nightly:
    runs-on: ubuntu-latest
    name: Dump and restore the remote database data.

    steps:
      - uses: actions/checkout@v4
      - name: Install scalingo CLI
        uses: ./.github/actions/install-scalingo-cli
        with:
          version: 1.49.0

      - name: Login with api-token
        run: scalingo login --api-token=${{ secrets.SCALINGO_API_TOKEN_SECNUM }}

      - name: Dump the remote database data and restore it to the local database.
        run: >-
          scalingo --region osc-secnum-fr1 --app if-prod-nightly-db run --size XL
          --file .github/scripts/nightly-db/restore-prod-dump.sh
          -- bash /tmp/uploads/restore-prod-dump.sh

      - name: Run DBT transformations
        if: always()
        run: >-
          scalingo --region osc-secnum-fr1 --app if-prod-nightly-db run --size XL
          --file .github/scripts/nightly-db/run-dbt.sh
          -- bash /tmp/uploads/run-dbt.sh

      - name: Vacuum and analyze nightly database
        if: always()
        run: >-
          scalingo --region osc-secnum-fr1 --app if-prod-nightly-db run --size XL
          --file .github/scripts/nightly-db/vacuum-analyze.sh
          -- bash /tmp/uploads/vacuum-analyze.sh
